services:
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports: # expose port 3000 to the outside world, so that we can actually access it
      - 3000:3000
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/floater
    volumes:
      - ./backend/src:/src

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
