# build -t cicd102 . - done
#$ docker run -it -p 3000:3000 -e MONGODB_CONNECTION_STRING='mongodb+srv://dr4gon:Km8KLGb4n1UfUf2i@cohort13.c9kc8z7.mongodb.net/floater?retryWrites=true&w=majority' -v "$(pwd)"/src:/src cicd102

services:
  backend:
    image: cicd102
    build: .
    ports: # expose port 3000 to the outside world, so that we can actually access it
      - 3000:3000
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/floater
    volumes:
      - ./src:/src

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
