# build -t cicd102 . - done
#$ docker run -it -p 3000:3000 -e MONGODB_CONNECTION_STRING='mongodb+srv://dr4gon:Km8KLGb4n1UfUf2i@cohort13.c9kc8z7.mongodb.net/floater?retryWrites=true&w=majority' -v "$(pwd)"/src:/src cicd102

services:
  backend:
    image: cicd102
    build: .
