@startuml AlexHousingPlatform
skinparam actorStyle awesome

class Person {
  String firstName
  String lastName
  Date birthDate
  User loggedInUser

  constructor(firstName, lastName, birthDate)
  ArrayList : size()
}

class User {
  String password
  String username
  Boolean loggedIn
}

Person --* User

class Server{
  boolean login(String username, String password)
}

User - Server : login >

@enduml
